on: push
name: Main workflow
env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
    # checkout cannot detect job
      # - uses: actions/checkout@v2
      - name: run full
        uses: sarisia/actions-status-discord@releases/v1
        with:
          title: "ToucanMan"
          description: "Message"
          nofail: false
          nodetail: true
          image: "https://user-images.githubusercontent.com/33576079/81886735-69e03f80-95d8-11ea-8828-fa10dda8afd1.png"
          color: 0xFFFFFF
          username: ToucanMan
