on: push
name: Main workflow
env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
    # checkout cannot detect job
      # - uses: actions/checkout@v2
      - name: run full
        uses: sarisia/actions-status-discord@releases/v1
        with:
          title: "ToucanMan"
          description: "According to all known laws of aviation, there is no way a bee should be able to fly. Its wings are too small to get its fat little body off the ground. The bee, of course, flies anyway because bees don't care what humans think is impossible.Paragraphs are the building blocks of papers. Many students define paragraphs in terms of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. In reality, though, the unity and coherence of ideas among sentences is what constitutes a paragraph. A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long. Ultimately, a paragraph is a sentence or group of sentences that support one main idea. In this handout, we will refer to this as the “controlling idea,” because it controls what happens in the rest of the paragraph."
          nofail: false
          nodetail: true
          image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Ramphastos_toco_Whipsnade_Zoo.jpg"
          color: 0xF05E16
          username: ToucanMan
          avatar_url: ${{ secrets.AVATAR_URL }}
